
java -jar tool/lib/htmlcompressor-1.5.3.jar src/about_en.htm > web/about_en.htm
java -jar tool/lib/htmlcompressor-1.5.3.jar src/blkconf.htm > web/blkconf.htm
java -jar tool/lib/htmlcompressor-1.5.3.jar src/cbs.htm > web/cbs.htm
java -jar tool/lib/htmlcompressor-1.5.3.jar src/changepw.htm > web/changepw.htm
java -jar tool/lib/htmlcompressor-1.5.3.jar src/conuser.htm > web/conuser.htm
java -jar tool/lib/htmlcompressor-1.5.3.jar src/dashboar.htm > web/dashboar.htm
java -jar tool/lib/htmlcompressor-1.5.3.jar src/datalog.htm > web/datalog.htm
java -jar tool/lib/htmlcompressor-1.5.3.jar src/datetime.htm > web/datetime.htm
java -jar tool/lib/htmlcompressor-1.5.3.jar src/devinfo.htm > web/devinfo.htm
java -jar tool/lib/htmlcompressor-1.5.3.jar src/diagnostic.htm > web/diagnostic.htm
java -jar tool/lib/htmlcompressor-1.5.3.jar src/eventlog.htm > web/eventlog.htm
java -jar tool/lib/htmlcompressor-1.5.3.jar src/eventlognew.htm > web/eventlognew.htm
java -jar tool/lib/htmlcompressor-1.5.3.jar src/evtrule.htm > web/evtrule.htm
java -jar tool/lib/htmlcompressor-1.5.3.jar src/extsens.htm > web/extsens.htm
java -jar tool/lib/htmlcompressor-1.5.3.jar src/frupdth.htm > web/frupdth.htm
java -jar tool/lib/htmlcompressor-1.5.3.jar src/ftp.htm > web/ftp.htm
java -jar tool/lib/htmlcompressor-1.5.3.jar src/http.htm > web/http.htm
java -jar tool/lib/htmlcompressor-1.5.3.jar src/ips.htm > web/ips.htm
java -jar tool/lib/htmlcompressor-1.5.3.jar src/ldap.htm > web/ldap.htm
java -jar tool/lib/htmlcompressor-1.5.3.jar src/login.htm > web/login.htm
java -jar tool/lib/htmlcompressor-1.5.3.jar src/loginset.htm > web/loginset.htm
java -jar tool/lib/htmlcompressor-1.5.3.jar src/master.htm > web/master.htm
java -jar tool/lib/htmlcompressor-1.5.3.jar src/network.htm > web/network.htm
java -jar tool/lib/htmlcompressor-1.5.3.jar src/outlet.htm > web/outlet.htm
java -jar tool/lib/htmlcompressor-1.5.3.jar src/outlets.htm > web/outlets.htm
java -jar tool/lib/htmlcompressor-1.5.3.jar src/pdus.htm > web/pdus.htm
java -jar tool/lib/htmlcompressor-1.5.3.jar src/pinghist.htm > web/pinghist.htm
java -jar tool/lib/htmlcompressor-1.5.3.jar src/pwpolicy.htm > web/pwpolicy.htm
java -jar tool/lib/htmlcompressor-1.5.3.jar src/resetdev.htm > web/resetdev.htm
java -jar tool/lib/htmlcompressor-1.5.3.jar src/role.htm > web/role.htm
java -jar tool/lib/htmlcompressor-1.5.3.jar src/serreach.htm > web/serreach.htm
java -jar tool/lib/htmlcompressor-1.5.3.jar src/smtp.htm > web/smtp.htm
java -jar tool/lib/htmlcompressor-1.5.3.jar src/snmp.htm > web/snmp.htm
java -jar tool/lib/htmlcompressor-1.5.3.jar src/ssh.htm > web/ssh.htm
java -jar tool/lib/htmlcompressor-1.5.3.jar src/ssl.htm > web/ssl.htm
java -jar tool/lib/htmlcompressor-1.5.3.jar src/telnet.htm > web/telnet.htm
java -jar tool/lib/htmlcompressor-1.5.3.jar src/updtfw.htm > web/updtfw.htm
java -jar tool/lib/htmlcompressor-1.5.3.jar src/usb.htm > web/usb.htm
java -jar tool/lib/htmlcompressor-1.5.3.jar src/users.htm > web/users.htm
java -jar tool/lib/htmlcompressor-1.5.3.jar src/vwdtlog.htm > web/vwdtlog.htm
java -jar tool/lib/htmlcompressor-1.5.3.jar src/vwdtlognew.htm > web/vwdtlognew.htm